config/routes.rb
Usmlemap::Application.routes.draw do
  get "profiles/show"
  devise_for :users
  resources :markers

  devise_scope :user do
    get 'register', :to => 'devise/registrations#new', as: :register
    get 'login', :to => 'devise/sessions#new', as: :login
    get 'logout', :to => 'devise/sessions#destroy', as: :logout
  end

  resources :user_friendships do
    member do
      put :accept
     end
  end

  root 'markers#index'

  get '/:id', to: 'profiles#show', as: :profile

end

app/models/marker.rb
class Marker < ActiveRecord::Base
	belongs_to :user

	validates :marker_content, presence: true,
							length: { minimum: 10 }

	validates :user_id, :marker_address, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :markers
  has_many :user_friendships
  has_many :friends, through: :user_friendships,
                    conditions: { user_friendships: { state: 'accepted' } }
  has_many :pending_user_friendships, class_name: 'UserFriendship',
                                  foreign_key: :user_id,
                                  conditions: { state: 'pending' }

  has_many :pending_friends, through: :pending_user_friendships, source: :friend

  validates :first_name, :last_name, :profile_name, presence: true

  validates :profile_name, uniqueness: true,
  							format: {
                  with: /^[a-zA-Z0-9_-]+$/,
  								message: "Must be formatted correctly.",
                  multiline: true
  							}

  def to_param
    profile_name
  end
end

app/models/user_friendship.rb
class UserFriendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'

	state_machine :state, initial: :pending do
		after_transition on: :accept, do: :send_acceptance_email

		state :requested

		event :accept do
			transition any => :accepted
		end
	end

	def self.request(user1, user2)
		transaction do
			friendship1 = create(user: user1, friend: user2, state: 'pending')
			friendship2 = create(user: user2, friend: user1, state: 'requested')

			friendship1.send_request_email
			friendship1
		end
	end

	def send_request_email
		UserNotifier.friend_requested(id).deliver
	end

	def send_acceptance_email
		UserNotifier.friend_accepted(id).deliver
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  

  # Next lines are from devise documentation to make it work!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  	def configure_permitted_parameters
  		registration_params = [:first_name, :last_name, :profile_name, :email, :password, :password_confirmation]
	    # devise_parameter_sanitizer.for(:sign_up) << :username
	    if params[:action] == 'update'
	      devise_parameter_sanitizer.for(:account_update) { 
	        |u| u.permit(registration_params << :current_password)
	      }
	    elsif params[:action] == 'create'
	      devise_parameter_sanitizer.for(:sign_up) { 
	        |u| u.permit(registration_params) 
	      }
	    end
	  end
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  before_action :set_marker, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]

  # GET /markers
  # GET /markers.json
  def index
    @markers = Marker.all
  end

  # GET /markers/1
  # GET /markers/1.json
  def show
  end

  # GET /markers/new
  def new
    @marker = Marker.new
  end

  # GET /markers/1/edit
  def edit
  end

  # POST /markers
  # POST /markers.json
  def create
    @marker = current_user.markers.new(marker_params)

    respond_to do |format|
      if @marker.save
        format.html { redirect_to @marker, notice: 'Marker was successfully created.' }
        format.json { render action: 'show', status: :created, location: @marker }
      else
        format.html { render action: 'new' }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /markers/1
  # PATCH/PUT /markers/1.json
  def update
    @marker = current_user.markers.find(params[:id])
    if params[:marker] && params[:marker].has_key?(:user_id)
      params[:marker].delete(:user_id)
    end
    respond_to do |format|
      if @marker.update(marker_params)
        format.html { redirect_to @marker, notice: 'Marker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end

    rescue ActiveRecord::RecordNotFound
      render file: 'public/404', status: :not_found
  end

  # DELETE /markers/1
  # DELETE /markers/1.json
  def destroy
    @marker.destroy
    respond_to do |format|
      format.html { redirect_to markers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marker
      @marker = Marker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marker_params
      params.require(:marker).permit(:marker_type, :marker_content, :marker_address, :start_date, :end_date, :user_id)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = User.find_by_profile_name(params[:id])
  	if @user
  		@markers = @user.markers.load
  		render action: :show
  	else
	  	render file: 'public/404', status: 404, formats: [:html]
	  end
  end
end

app/controllers/user_friendships_controller.rb
class UserFriendshipsController < ApplicationController
	before_filter :authenticate_user!

	def index
		@user_friendships = current_user.user_friendships.load
	end

	def new
		if params[:friend_id]
			@friend = User.where(profile_name: params[:friend_id]).first
			raise ActiveRecord::RecordNotFound if @friend.nil?
			@user_friendship = current_user.user_friendships.new(friend: @friend)
		else
			flash[:error] = "Friend Required"
		end

		rescue ActiveRecord::RecordNotFound
			render file: 'public/404', status: :not_found
	end

	def create
		if params[:user_friendship] && params[:user_friendship].has_key?(:friend_id)
			@friend = User.where(profile_name: params[:user_friendship][:friend_id]).first
			@user_friendship = current_user.user_friendships.new(friend: @friend)
			@user_friendship.save
			flash[:success] = "You are now friends with #{@friend.first_name}"
		else
			flash[:error] = "Friend Required"
			redirect_to root_path
		end
	end

	def accept
		@user_friendship = current_user.user_friendships.find(params[:id])
		if @user_friendship.accept!
			flash[:success] = "You are now friends with #{@user_friendship.friend.first_name}"
		else
			flash[:error] = "Sorry, but #{@user_friendship.friend.first_name} doesn't want to be your friend"
		end
		redirect_to user_friendships_path
	end

	def edit
		@user_friendship = current_user.user_friendships.find(params[:id])
		@friend = @user_friendship.friend
	end
end
 

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(type)
		case type
		when :alert
			"status-red"
		when :notice
			"status-green"
		else
			"status-blue"
		end
	end
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/user_friendships_helper.rb
module UserFriendshipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Usmlemap</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed navbar-fluid">
  <nav>
    <ul>
      <li class="navbar-title">
        <%= link_to "USMLEMAP", root_path %>
      </li>
    </ul>
    <ul>
    <% if user_signed_in? %>
    	<li><%= link_to current_user.first_name, edit_user_registration_path %></li>
      <li><%= link_to "Friends", user_friendships_path %></li>
    	<li><%= link_to "Logout", logout_path %></li>
    <% else %>
    	<li><%= link_to "Login", login_path %></li>
    	<li><%= link_to "Signup", register_path %></li>
    <% end %>
    </ul>
  </nav>
</div>


<div class="container content">
	<%= yield %>

</div>
<% flash.each do |type, message| %>
  <script type="text/javascript">
    k$.status({
      text: '<%= message %>',
      delay: 2000,
      type: '<%= flash_class type %>',
      id: 'token'
    });
  </script>
<% end %>


</body>
</html>

app/views/markers/_form.html.erb
<%= form_for(@marker) do |f| %>
  <% if @marker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@marker.errors.count, "error") %> prohibited this marker from being saved:</h2>

      <ul>
      <% @marker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :marker_type %>
    <%= f.text_field :marker_type %>
  </div>
  <div class="field">
    <%= f.label :marker_content %>
    <%= f.text_area :marker_content %>
  </div>
  <div class="field">
    <%= f.label :marker_address %>
    <%= f.text_field :marker_address %>
  </div>
  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/markers/edit.html.erb
<h1>Editing marker</h1>

<%= render 'form' %>

<%= link_to 'Show', @marker %> |
<%= link_to 'Back', markers_path %>

app/views/markers/index.html.erb
<h3>Listing markers</h3>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Marker type</th>
      <th>Marker content</th>
      <th>Marker address</th>
      <th>Start date</th>
      <th>End date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @markers.each do |marker| %>
      <tr>
        <td><%= link_to marker.user.first_name, profile_path(marker.user) %></td>
        <td><%= marker.marker_type %></td>
        <td><%= marker.marker_content %></td>
        <td><%= marker.marker_address %></td>
        <td><%= marker.start_date %></td>
        <td><%= marker.end_date %></td>
        <td><%= link_to 'Show', marker, :class => 'button button-green' %></td>
        <td><%= link_to 'Edit', edit_marker_path(marker), :class => 'button button-yellow' %></td>
        <td><%= link_to 'Destroy', marker, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'button button-red' %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'New Marker', new_marker_path, :class => 'button button-small button-blue' %>

app/views/markers/new.html.erb
<h1>New marker</h1>

<%= render 'form' %>

<%= link_to 'Back', markers_path %>

app/views/markers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User</strong>
  <%= @marker.user_id %>
</p>

<p>
  <strong>Marker type:</strong>
  <%= @marker.marker_type %>
</p>

<p>
  <strong>Marker content:</strong>
  <%= @marker.marker_content %>
</p>

<p>
  <strong>Marker address:</strong>
  <%= @marker.marker_address %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @marker.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @marker.end_date %>
</p>

<%= link_to 'Edit', edit_marker_path(@marker) %> |
<%= link_to 'Back', markers_path %>

app/views/profiles/show.html.erb
<div class="header">
	<h3><%= @user.profile_name %></h3>
	<%= link_to "Add Friend", new_user_friendship_path(friend_id: @user) %>
</div>
<% if @markers %>
	<% @markers.each do |marker| %>
		<%= marker.marker_type %><br />
	<% end %>
<% end %>

app/views/user_friendships/create.html.erb
<h2>Hi</h2>

app/views/user_friendships/edit.html.erb
<div>
	<h1>Viewing Friendship</h1>
</div>

<% if @user_friendship.requested? %>
	<h3> Do you really want to be friends with <%= @friend.first_name %>?<h3>
<% end %>


<div>
	<% if @user_friendship.requested? %>
		<%= form_for @user_friendship, url: accept_user_friendship_path(@user_friendship), method: :put do |form| %>
			<%= submit_tag "Accept Friendship", class: 'button button-green'  %>
		<% end %>
	<% end %>
</div>

app/views/user_friendships/index.html.erb
<h3>Friends</h3>
<% @user_friendships.each do |friendship| %>
	<%= friendship.friend.first_name %><br />
	<p>Friendship is <%= friendship.state %>.</p>
	<%= link_to "Delete Request!", edit_user_friendship_path(friendship) %>
<% end %>

app/views/user_friendships/new.html.erb
<h3>Hello</h3>
<% if @friend %>
	<%= @friend.first_name %>

	<p>Do you really want to be friends with <%= @friend.first_name %>?</p>
	<%= form_for @user_friendship, method: :post do |form| %>
		<%= form.hidden_field :friend_id, value: @friend.profile_name %>
		<%= submit_tag "Yes, Add Friend", class: 'button button-blue' %>
		<%= link_to "Cancel", profile_path(@friend), class: 'button button-red' %>
	<% end %>
<% end %>

app/views/user_notifier/friend_accepted.html.erb
<h3>Friend request accepted!</h3>
<p>Hi, <%= @friend.first_name %> just accepted your friend request! Now you're friends on USMLEAID.</p>

app/views/user_notifier/friend_requested.html.erb
<h3>You have a new friend request!</h3>

<p>Hi, <%= @user.first_name %> wants to be your friend on USMLEMAP.</p>